let level1;

function loadLevel(){
    level1 = new Level(
        [
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),

            new MiniChicken(),
            new MiniChicken(),
            new MiniChicken(),
            new MiniChicken(),
            new MiniChicken(),
            new MiniChicken(),
        ],
        [
            new Cloud(),
        ],
        [
            new BackgroundObject('img/5_background/layers/air.png', -719, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719, 100),
            new BackgroundObject('img/5_background/layers/air.png', 0, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719*2, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*2, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*2, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*2, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719*3, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*3, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*3, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*3, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719*4, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*4, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*4, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*4, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719*5, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*5, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*5, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*5, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719*6, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*6, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*6, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*6, 100),
            new BackgroundObject('img/5_background/layers/air.png', 719*7, 100),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*7, 100),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*7, 100),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*7, 100),
        ],
        [
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
            new Coins(),
        ],
        [
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
            new Bottels(),
        ],
        [
            new BackgroundObject('img/9_intro_outro_screens/game_over/game over.png', 0, 100),
        ],
        [
            new BackgroundObject('img/9_intro_outro_screens/win/won_2.png', 0, 100),        
        ],
        [
            new BackgroundObject('img/9_intro_outro_screens/start/startscreen_1.png', 0, 100),        
        ]
    );
}


